#include "problem2.hpp"

int16_t euler::problem2::id() { return 2; }

std::string euler::problem2::caption() { return "Even Fibonacci numbers"; }

std::string euler::problem2::description() {
  return "Each new term in the Fibonacci sequence is generated by adding the\n"
         "previous two terms. By starting with 1 and 2, the first 10 terms\n"
         "will be:\n"
         "\n"
         "\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
         "\n"
         "By considering the terms in the Fibonacci sequence whose values do\n"
         "not exceed four million, find the sum of the even-valued terms.\n";
}

uint64_t euler::problem2::run() {
  return 0;
}
